### PR TITLE
Use correct alert example

### PR DESCRIPTION
**Pull request by qrilka**
Noticed this while trying out alerts

### CODE REVIEW

**Review by lpaulmp — CHANGES_REQUESTED** [review]
@qrilka the change looks good but I can't imagine what the output should look like, would you mind to add a screenshot of the metric/alert, please?

**Comment by qrilka** [comment]
@lpaulmp Do you mean like adding an image into a config file or just post it here?

**Comment by lpaulmp** [comment]
@qrilka yes like an image or an output where I could see how it works.

**Comment by qrilka** [comment]
Here it is in Prometheus alerts:
sc
And here fired alert in alertmanager:
sc
And the same alert in Slack:
sc

All I did just fired a couple of ordinary requests with status 200 and also a couple of bad requests returning 400.

**Comment by lpaulmp** [comment]
@qrilka thanks the alert looks awesome!

**Review by lpaulmp — APPROVED** [review]

**Pull request merged**
